# Travis CI setup for turbinesFoam

sudo: required
dist: trusty
language: cpp

before_install:
    - sudo add-apt-repository http://www.openfoam.org/download/ubuntu
    - sudo apt-get update -qq
    - sudo apt-get install -qq openfoam30 --allow-unauthenticated
    - sudo apt-get install -qq python-numpy python-nose python-pandas
    - sudo pip install pandas -U

install:
    - source /opt/openfoam30/etc/bashrc
    - ./Allwmake

before_script:
    - source /opt/openfoam30/etc/bashrc

script:
    - ./Alltest
